version: '3.1'

services:
  springboot:
    image: gurumadala/spring-boot-mongo:latest
    ports:
      - 8081:8080
    working_dir: /opt/app
    depends_on:
      - mongo
    networks:
    - springappnetwork

  mongo:
    image: mongo
    volumes:
      - mongodb:/data/db
    restart: always
    networks:
    - springappnetwork

volumes:
  mongodb:
    external: false

networks:
  springappnetwork:
    external: false
