version: '3.1'

services:
  springboot:
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=testdb
    - MONGO_DB_PASSWORD=testdb123

  mongo:
    environment:
    - MONGO_INITDB_ROOT_USERNAME=testdb
    - MONGO_INITDB_ROOT_PASSWORD=testdb123
